name: Myo's Coding Blog
description: Myo's Coding Blog
meta_description: "Blogging about things a full stack developer encounter"

markdown: kramdown
# highlighter: rogue
logo: false
paginate: 15
baseurl: /
domain_name: 'http://mkyaw.github.io'
google_analytics: ''
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://mkyaw.github.io'
author:         'Myo Kyaw'
